import os
import time
import xml.etree.ElementTree as ET
import hashlib

# --- CONFIGURATION ---
STATIC_SUFFIX = " (Map)"  # Suffix for the generated map file
MD_EXT = ".md"

# We use this variable to prevent the code block from breaking in the chat interface
# It simply creates a string of three backticks
TICKS = "`" * 3

def get_file_mtime(path):
    """Returns the modification time of a file."""
    return os.path.getmtime(path)

def parse_gpx(filepath):
    """
    Parses a GPX file to extract waypoints (lat, lon, name).
    Returns a tuple: (list_of_marker_strings, (avg_lat, avg_lon))
    """
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
        
        # GPX files often have namespaces that make finding tags strict.
        # We use ".//{*}tagname" to find tags regardless of namespace.
        waypoints = []
        lats = []
        lons = []
        
        for wpt in root.findall(".//{*}wpt"):
            lat_str = wpt.get('lat')
            lon_str = wpt.get('lon')
            
            if lat_str and lon_str:
                lat = float(lat_str)
                lon = float(lon_str)
                
                # Find the <name> tag
                name_tag = wpt.find(".//{*}name")
                # Sanitize the name (escape quotes, trim whitespace)
                raw_name = name_tag.text if name_tag is not None else "Unnamed"
                safe_name = raw_name.replace('"', '\\"').strip()
                
                # Format: - [lat, lon, "name"]
                waypoints.append(f"  - [{lat}, {lon}, \"{safe_name}\"]")
                lats.append(lat)
                lons.append(lon)
            
        if not waypoints:
            return [], (0, 0)
            
        # Calculate center point for the map
        avg_lat = sum(lats) / len(lats)
        avg_lon = sum(lons) / len(lons)
        
        return waypoints, (avg_lat, avg_lon)
        
    except Exception as e:
        print(f"Error parsing {filepath}: {e}")
        return [], (0, 0)

def generate_static_content(base_name, waypoints, center_coords):
    """Generates the Markdown content for the STATIC map file."""
    avg_lat, avg_lon = center_coords
    markers_str = "\n".join(waypoints)
    
    # Generate a unique hash for the map ID to prevent collisions in Obsidian
    map_hash = hashlib.md5(base_name.encode()).hexdigest()[:8]
    
    # We construct the content string dynamically
    content = f"""---
related: "[[{base_name}]]"
tags:
  - auto-generated
---
> [!WARNING] DO NOT EDIT THIS FILE
> This file is automatically regenerated from the GPX source by the `refresh_maps.py` script.
> Any manual changes here will be overwritten.
> Go to [[{base_name}]] for your main notes.

{TICKS}leaflet
id: map_{map_hash}
lat: {avg_lat:.6f}
long: {avg_lon:.6f}
zoom: 11
height: 600px
osmLayer: true
marker:
{markers_str}
{TICKS}
"""
    return content

def generate_main_content(static_filename_base):
    """Generates the content for the MAIN note (only if it doesn't exist)."""
    return f"""---
related: "[[{static_filename_base}]]"
---
# {static_filename_base.replace(STATIC_SUFFIX, "")}

Your manual notes go here.
"""

def scan_and_refresh(root_dir):
    print(f"Scanning for GPX files in: {root_dir}")
    count_updated = 0
    count_created = 0
    
    # os.walk visits every folder recursively
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.lower().endswith(".gpx"):
                base_name = os.path.splitext(filename)[0]
                gpx_path = os.path.join(dirpath, filename)
                
                # Define the target filenames
                static_name = f"{base_name}{STATIC_SUFFIX}{MD_EXT}"
                main_name = f"{base_name}{MD_EXT}"
                
                static_path = os.path.join(dirpath, static_name)
                main_path = os.path.join(dirpath, main_name)
                
                # --- LOGIC 1: Handle the Static Map File ---
                gpx_mtime = get_file_mtime(gpx_path)
                should_regenerate = False
                
                if not os.path.exists(static_path):
                    print(f"[NEW MAP] Generating: {static_name}")
                    should_regenerate = True
                else:
                    static_mtime = get_file_mtime(static_path)
                    # If GPX is newer than the Static Markdown map, regenerate
                    if gpx_mtime > static_mtime:
                        print(f"[UPDATE] GPX changed. Refreshing: {static_name}")
                        should_regenerate = True
                
                if should_regenerate:
                    markers, center = parse_gpx(gpx_path)
                    if markers:
                        content = generate_static_content(base_name, markers, center)
                        with open(static_path, "w", encoding="utf-8") as f:
                            f.write(content)
                        count_updated += 1
                
                # --- LOGIC 2: Handle the Main Note File ---
                # Only create if it does not exist (do not overwrite user notes)
                if not os.path.exists(main_path):
                    print(f"[NEW NOTE] Creating main entry: {main_name}")
                    # Link to the base name of the static file (no extension for wiki link)
                    static_link_target = f"{base_name}{STATIC_SUFFIX}"
                    content = generate_main_content(static_link_target)
                    with open(main_path, "w", encoding="utf-8") as f:
                        f.write(content)
                    count_created += 1

    print(f"\nScan Complete. Maps Refreshed: {count_updated}. New Notes Created: {count_created}.")

if __name__ == "__main__":
    # Get the directory where this script is running
    current_dir = os.getcwd()
    scan_and_refresh(current_dir)
    